CREATE TABLE foods (
    food_id serial PRIMARY KEY,
    food_name VARCHAR (100) NOT NULL,
    description VARCHAR (255),
    recipe TEXT NOT NULL,
    instructions TEXT NOT NULL,
    image_url VARCHAR (255) NOT NULL
);

INSERT INTO foods (food_name, description, recipe, instructions, image_url) VALUES 
('Chicken Adobo', 'The classic Filipino savory stew.', 'Soy sauce, Vinegar, Garlic, Peppercorns, Bay leaves.', 'Marinate chicken. Brown the meat. Simmer in the marinade until tender.', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Adobo_DSCF4391.jpg'),
('Sinigang na Baboy', 'A sour and savory soup made with pork and tamarind.', 'Pork belly, Tamarind base, Kangkong, Radish, Tomato.', 'Boil pork until tender. Add tamarind mix. Add vegetables last.', 'https://asianinspirations.com.au/wp-content/uploads/2022/07/R02988-Pork-Sinigang.jpg'),
('Halo-Halo', 'The ultimate Filipino iced dessert.', 'Shaved ice, Evaporated milk, Ube, Leche Flan, Beans.', 'Layer ingredients in a tall glass. Top with ice, milk, and ube.', 'https://graceland.ph/wp-content/uploads/2023/05/HALO-HALO-SPECIAL.jpg'),
('Sisig', 'Sizzling chopped pork face and ears.', 'Pork mask, Onion, Chili, Calamansi, Mayo (optional).', 'Boil then grill the pork. Chop finely. Sauté with onions and chili.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Authentic_Kapampangan_Sisig.jpg/2560px-Authentic_Kapampangan_Sisig.jpg'),
('Kare-Kare', 'Oxtail stew in peanut sauce.', 'Oxtail, Peanut butter, Annatto, String beans, Eggplant.', 'Tenderize meat. Sauté aromatics and add peanut paste. Serve with bagoong.', 'https://browngirlveganeats.com/wp-content/uploads/2023/10/photo1696939990-1.jpeg'),
('Pancit', 'Stir-fried egg noodles with vegetables and meat.', 'Canton noodles, Soy sauce, Mixed vegetables, Chicken, Shrimp.', 'Sauté meat and vegetables. Add noodles and sauce. Stir-fry until cooked.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Pancit_Ilonggo_Style_-_12110747826.jpg/2560px-Pancit_Ilonggo_Style_-_12110747826.jpg'),
('Lechon Kawali', 'Crispy deep-fried pork belly.', 'Pork belly, Salt, Pepper, Bay leaves, Oil for frying.', 'Boil pork with spices until tender. Deep fry until crispy.', 'https://www.seriouseats.com/thmb/tCtlpSDJ3QYZfYrWKT6xy43RVJ4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/20210508-lechon-kawali-melissa-hom-2-inchChunks-seriouseats-1d53c12cee234305b921362e2106bf29.jpg'),
('Bibingka', 'Traditional Filipino rice cake.', 'Rice flour, Coconut milk, Sugar, Eggs, Grated coconut.', 'Mix ingredients. Pour into banana leaf-lined molds. Bake until set.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Bibingka-6.jpg/960px-Bibingka-6.jpg'),
('Lumpiang Shanghai', 'Filipino-style spring rolls with ground pork filling.', 'Ground pork, Carrot, Onion, Garlic, Spring roll wrappers.', 'Mix filling ingredients. Wrap in spring roll wrappers. Deep fry until golden.', 'https://themayakitchen.com/wp-content/uploads/2019/10/LUMPIANG-SHANGHAI.jpg'),
('Bicol Express', 'Spicy pork stew in coconut milk.', 'Pork, Coconut milk, Chili peppers, Shrimp paste, Garlic.', 'Sauté pork and garlic. Add coconut milk and chilies. Simmer until cooked.', 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Bicol_Express.jpg'),
('Turon', 'Fried banana spring rolls with caramelized sugar.', 'Saba bananas, Brown sugar, Spring roll wrappers, Oil for frying.', 'Wrap banana slices with brown sugar in spring roll wrappers. Fry until golden.', 'https://themayakitchen.com/wp-content/uploads/2019/10/TURON.jpg'),
('Puto', 'Steamed rice cakes, often served as a side dish.', 'Rice flour, Sugar, Baking powder, Coconut milk, Cheese (optional).', 'Mix ingredients. Pour into molds. Steam until cooked.', 'https://flouredframe.com/wp-content/uploads/2019/12/filipino-puto-15.jpg'),
('Patatim', 'A Filipino-Chinese braised pork hock dish slow-cooked until very tender in a savory-sweet sauce.', 'Pork, Soy sauce, Star anise, laurel, pepper, garlic, onions, brown sugar', 'Marinate pork. Sear until brown. Simmer with spices and sauce until tender.', 'https://delivery.vikings.ph/cdn/shop/products/PataTimWhole_0b8887e1-e0c5-43da-9a11-7bba479c982a_800x.jpg?v=1600093113'),
('Empanada', 'A stuffed bread or pastry baked or fried.', 'Flour, Ground meat, Potatoes, Carrots, Onions, Spices.', 'Prepare dough. Cook filling. Assemble and bake or fry until golden brown.', 'https://cdn-ilddihb.nitrocdn.com/MgqZCGPEMHvMRLsisMUCAIMWvgGMxqaj/assets/images/optimized/rev-e5c3642/www.goya.com/wp-content/uploads/2023/10/empanadas-beef-turnovers.jpg'),
('Callos', 'A Spanish-influenced Filipino stew made with tripe, chickpeas, and chorizo.', 'Beef tripe, Chickpeas, Chorizo, Tomato sauce, Bell peppers.', 'Boil tripe until tender. Sauté chorizo and vegetables. Simmer with tripe and sauce.', 'https://www.simpol.ph/wp-content/uploads/2025/06/CALLOS.jpg'),
('Arroz Caldo', 'A comforting Filipino rice porridge flavored with ginger and garlic.', 'Rice, Chicken, Ginger, Garlic, Fish sauce, Green onions.', 'Sauté garlic and ginger. Add chicken and rice. Simmer until rice is soft. Garnish with green onions.', 'https://www.eatwithcarmen.com/wp-content/uploads/2024/09/Arroz-Caldo-with-Chicken.jpg'),
('Laing', 'A spicy dish made from dried taro leaves cooked in coconut milk.', 'Dried taro leaves, Coconut milk, Chili peppers, Garlic, Shrimp paste.', 'Sauté garlic and chili. Add coconut milk and dried taro leaves. Simmer until cooked.', 'https://www.kawalingpinoy.com/wp-content/uploads/2019/05/laing-9.jpg'),
('Pancit Malabon', 'A Filipino noodle dish known for its thick rice noodles and seafood toppings.', 'Thick rice noodles, Shrimp, Squid, Fish sauce, Annatto oil, Vegetables.', 'Cook noodles. Sauté seafood and vegetables. Mix with noodles and sauce. Top with more seafood.', 'https://www.todaysdelight.com/wp-content/uploads/2018/05/pancit-malabon-recipe-1724-500x500.jpg'),
('Dinuguan', 'A savory Filipino stew made from pork and pig''s blood.', 'Pork, Pig''s blood, Vinegar, Garlic, Chili peppers.', 'Sauté garlic and pork. Add pig''s blood and vinegar. Simmer until cooked.', 'https://assets.unileversolutions.com/recipes-v2/110821.jpg'),
('Mechado', 'A Filipino beef stew braised in a tomato-based sauce.', 'Beef, Tomato sauce, Soy sauce, Potatoes, Carrots.', 'Sear beef. Sauté vegetables. Simmer beef in tomato sauce until tender.', 'https://www.unileverfoodsolutions.com.ph/dam/global-ufs/mcos/SEA/calcmenu/recipes/PH-recipes/chicken-&-other-poultry-dishes/mechado-baka/mechado-baka-main-banner.jpg');
